### ISSUE TITLE
Column View Cookie Presets

### ISSUE THREAD

**Issue by soif** [soif/OpenWrtTOH#3]
Allow to store (with a custom name) and recall a column views selection into up to 3 presets, stored as JSON in a cookie.

**Comment by richb-hanover** [comment]
Here's another approach to building presets... It has a couple parts (which I haven't thought through deeply... I may have the details wrong, but I think this could work...)

1. Have the ToH URL take a query string something like: `columns={col1, col2, col3}`
2. Display the currently selected columns in the `columns=...` query string in the browser's URL bar
3. Update that `columns=...` query string as various columns are added/removed

This makes it straightforward for people to create custom ToH's. They can simply start with one that's close to what they want, add/remove columns, then save the resulting URL from the browser to pass along to their friends.

(I think approach also permits another "filter" query string, that would only include Brand=NETGEAR or RAM=4...)

**Comment by soif** [comment]
Great suggestion @richb-hanover ! 👍 

**I've just implemented this in v1.4** (as well as filters preset, filters features, and columns preset).
BTW I had to refactor the whole code for this, _but anyway it had to be done!_

Regarding the 'filter' (this name is currently used in the URL as the filters preset), I can't easily implement it as you suggested, because the tabulator filters, are more complexs (ie not always "=", but can be "like", or a more complex dedicated filter function, ie:flashmb). Encoding it in the URL would be a nightmare. 
On the other hand, I already include filters 'features' (which are sets of filters) in the URL.

_FYI: I still intend to implements User's presets as cookies, as this should be easy and certainly useful._

--------
Do me a favor, please:
- If you can, grab me answers for #2 
- As you are GH fork/commit used, would you please check my english texts, and fix them where needed 🙏
